# Generated by Django 3.1 on 2020-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(),
        ),
    ]
