# Generated by Django 3.1 on 2020-10-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201031_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_name',
            new_name='user_email',
        ),
    ]
